# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f68d6301fe85db27ee90d057aebdfec9cb031aedc7faa76df56e75c7b9717dc9a42d2a1945e647802094d7563300163edb1a26a3acf8b846f6977aacac7953b5

test:
  secret_key_base: abcfa81a972e7322cde39da07ee13c494bf172471f47a7d407d6fc52078a8d9d7dbc0947062702b5c3817abd8e2a40ec6ded1c2ae3d1e3b0b066344af8553ace

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
